// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: jflex.jflex

package paboomi.practica1_compi1_1s_2026.backend.analyzer;
import java_cup.runtime.*;
import java.util.*;

@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\1\6\1\0\1\7\1\10\1\0\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\12\21\2\0"+
    "\1\22\1\23\1\24\2\0\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\2\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\36\1\54\1\0\1\55\2\0"+
    "\1\56\1\0\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\2\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\36\1\54\1\0\1\57\10\0\1\3\252\0"+
    "\2\60\115\0\1\61\u01a8\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\17\20\1\21\2\1\1\22\1\0\1\23"+
    "\6\0\1\24\1\0\1\25\1\26\1\27\3\20\1\0"+
    "\4\20\1\0\6\20\1\0\3\20\2\30\1\20\1\0"+
    "\2\20\1\31\6\0\1\32\1\20\1\0\3\20\1\0"+
    "\2\20\1\0\2\20\1\33\1\0\1\33\3\20\1\0"+
    "\4\20\2\0\4\20\1\0\1\34\1\20\1\35\3\0"+
    "\1\20\1\0\3\20\2\0\2\20\1\0\4\20\3\0"+
    "\3\20\1\0\1\36\3\20\2\0\4\20\1\0\1\20"+
    "\3\0\2\37\3\20\2\0\2\20\1\0\3\20\1\0"+
    "\2\40\1\0\1\20\1\41\1\20\1\0\3\20\2\0"+
    "\2\20\1\42\1\20\1\0\1\20\3\0\3\20\2\0"+
    "\1\20\2\43\3\20\2\0\1\20\2\44\3\20\2\0"+
    "\3\20\1\0\1\20\3\0\1\45\4\20\1\0\1\20"+
    "\1\0\1\45\1\46\3\20\2\0\1\47\3\20\1\0"+
    "\1\20\2\50\1\0\3\20\1\0\1\51\3\0\1\46"+
    "\2\0\2\20\1\0\2\52\2\20\1\0\2\53\3\20"+
    "\1\0\1\20\3\0\2\20\1\0\2\54\2\55\3\20"+
    "\4\0\2\20\1\0\2\20\1\0\2\20\1\0\2\56"+
    "\1\20\2\0\2\20\1\0\1\20\1\0\3\20\4\0"+
    "\2\20\1\0\1\20\2\57\2\20\1\0\1\20\2\0"+
    "\2\20\1\0\1\20\1\0\1\20\1\60\1\20\4\0"+
    "\2\20\1\0\3\20\1\0\2\61\1\0\2\20\1\0"+
    "\1\20\1\0\3\20\4\0\1\62\1\20\1\0\3\20"+
    "\2\0\1\63\1\20\1\0\3\20\3\0\3\20\1\0"+
    "\1\62\1\0\1\63\1\20\1\0\3\20\1\0\1\64"+
    "\1\20\1\0\1\64\1\20\1\0\2\20\1\0\2\65"+
    "\1\0\1\66\2\20\3\0\2\67\2\20\1\0\2\70"+
    "\1\20\1\0\2\71\2\20\2\0\2\20\2\0\2\20"+
    "\1\0\2\72\2\20\2\0\1\20\2\73\1\0\2\20"+
    "\1\0\2\20\2\0\1\20\1\0\2\20\1\0\1\74"+
    "\1\20\1\0\1\74\1\20\1\0\1\75\1\20\1\0"+
    "\1\20\1\0\1\20\1\75\1\20\1\0\2\76\1\20"+
    "\2\77\1\20\1\100";

  private static int [] zzUnpackAction() {
    int [] result = new int[472];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\u015e"+
    "\0\62\0\62\0\62\0\62\0\62\0\62\0\62\0\u0190"+
    "\0\u01c2\0\u01f4\0\u0226\0\u0258\0\u028a\0\u02bc\0\u02ee\0\u0320"+
    "\0\u0352\0\u0384\0\u03b6\0\u03e8\0\u041a\0\u044c\0\u047e\0\u04b0"+
    "\0\u04e2\0\u0514\0\u0546\0\u0578\0\u05aa\0\62\0\310\0\62"+
    "\0\u05dc\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6\0\62\0\u0708"+
    "\0\62\0\62\0\62\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802"+
    "\0\u0834\0\u0866\0\u0898\0\u08ca\0\u08fc\0\u092e\0\u0960\0\u0992"+
    "\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u028a\0\62"+
    "\0\u0af0\0\u0b22\0\u0b54\0\u0b86\0\62\0\u0bb8\0\u0bea\0\u0c1c"+
    "\0\u0c4e\0\u0c80\0\u0cb2\0\u0708\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a"+
    "\0\u0dac\0\u0dde\0\u0e10\0\u0e42\0\u0e74\0\u0ea6\0\u0ed8\0\u0f0a"+
    "\0\u0f3c\0\u0f6e\0\u0fa0\0\u0fd2\0\u1004\0\u1036\0\u1068\0\u109a"+
    "\0\u10cc\0\u10fe\0\u1130\0\u1162\0\u1194\0\u11c6\0\u11f8\0\u122a"+
    "\0\u125c\0\u028a\0\u128e\0\62\0\u12c0\0\u12f2\0\u1324\0\u1356"+
    "\0\u1388\0\u13ba\0\u13ec\0\u141e\0\u1450\0\u1482\0\u14b4\0\u14e6"+
    "\0\u1518\0\u154a\0\u157c\0\u15ae\0\u15e0\0\u1612\0\u1644\0\u1676"+
    "\0\u16a8\0\u16da\0\u170c\0\u173e\0\u028a\0\u1770\0\u17a2\0\u17d4"+
    "\0\u1806\0\u1838\0\u186a\0\u189c\0\u18ce\0\u1900\0\u1932\0\u1964"+
    "\0\u1996\0\u19c8\0\u19fa\0\u028a\0\62\0\u1a2c\0\u1a5e\0\u1a90"+
    "\0\u1ac2\0\u1af4\0\u1b26\0\u1b58\0\u1b8a\0\u1bbc\0\u1bee\0\u1c20"+
    "\0\u1c52\0\u028a\0\62\0\u1c84\0\u1cb6\0\u028a\0\u1ce8\0\u1d1a"+
    "\0\u1d4c\0\u1d7e\0\u1db0\0\u1de2\0\u1e14\0\u1e46\0\u1e78\0\u028a"+
    "\0\u1eaa\0\u1edc\0\u1f0e\0\u1f40\0\u1f72\0\u1fa4\0\u1fd6\0\u2008"+
    "\0\u203a\0\u206c\0\u209e\0\u20d0\0\u028a\0\62\0\u2102\0\u2134"+
    "\0\u2166\0\u2198\0\u21ca\0\u21fc\0\u028a\0\62\0\u222e\0\u2260"+
    "\0\u2292\0\u22c4\0\u22f6\0\u2328\0\u235a\0\u238c\0\u23be\0\u23f0"+
    "\0\u2422\0\u2454\0\u2486\0\u028a\0\u24b8\0\u24ea\0\u251c\0\u254e"+
    "\0\u2580\0\u25b2\0\u25e4\0\62\0\u028a\0\u2616\0\u2648\0\u267a"+
    "\0\u26ac\0\u26de\0\u028a\0\u2710\0\u2742\0\u2774\0\u27a6\0\u27d8"+
    "\0\u028a\0\62\0\u280a\0\u283c\0\u286e\0\u28a0\0\u28d2\0\u028a"+
    "\0\u2904\0\u2936\0\u2968\0\62\0\u299a\0\u29cc\0\u29fe\0\u2a30"+
    "\0\u2a62\0\u028a\0\62\0\u2a94\0\u2ac6\0\u2af8\0\u028a\0\62"+
    "\0\u2b2a\0\u2b5c\0\u2b8e\0\u2bc0\0\u2bf2\0\u2c24\0\u2c56\0\u2c88"+
    "\0\u2cba\0\u2cec\0\u2d1e\0\u2d50\0\u2d82\0\u028a\0\62\0\u2db4"+
    "\0\u2de6\0\u2e18\0\u2e4a\0\u2e7c\0\u2eae\0\u2ee0\0\u2f12\0\u2f44"+
    "\0\u2f76\0\u2fa8\0\u2fda\0\u300c\0\u303e\0\u3070\0\u30a2\0\u028a"+
    "\0\62\0\u30d4\0\u3106\0\u3138\0\u316a\0\u319c\0\u31ce\0\u3200"+
    "\0\u3232\0\u3264\0\u3296\0\u32c8\0\u32fa\0\u332c\0\u335e\0\u3390"+
    "\0\u33c2\0\u33f4\0\u3426\0\u3458\0\u028a\0\62\0\u348a\0\u34bc"+
    "\0\u34ee\0\u3520\0\u3552\0\u3584\0\u35b6\0\u35e8\0\u361a\0\u364c"+
    "\0\u367e\0\u36b0\0\u36e2\0\u3714\0\u3746\0\u3778\0\u37aa\0\u37dc"+
    "\0\u380e\0\u3840\0\u3872\0\u38a4\0\u38d6\0\u3908\0\u393a\0\u028a"+
    "\0\62\0\u396c\0\u399e\0\u39d0\0\u3a02\0\u3a34\0\u3a66\0\u3a98"+
    "\0\u3aca\0\u3afc\0\u3b2e\0\u3b60\0\u3b92\0\u3bc4\0\u028a\0\u3bf6"+
    "\0\u3c28\0\u3c5a\0\u3c8c\0\u3cbe\0\u3cf0\0\u3d22\0\u028a\0\u3d54"+
    "\0\u3d86\0\u3db8\0\u3dea\0\u3e1c\0\u3e4e\0\u3e80\0\u3eb2\0\u3ee4"+
    "\0\u3f16\0\u3f48\0\u3f7a\0\62\0\u3fac\0\62\0\u3fde\0\u4010"+
    "\0\u4042\0\u4074\0\u40a6\0\u40d8\0\u028a\0\u410a\0\u413c\0\62"+
    "\0\u416e\0\u41a0\0\u41d2\0\u4204\0\u4236\0\u028a\0\62\0\u4268"+
    "\0\u028a\0\u429a\0\u42cc\0\u42fe\0\u4330\0\u4362\0\u028a\0\62"+
    "\0\u4394\0\u43c6\0\u43f8\0\u028a\0\62\0\u442a\0\u445c\0\u028a"+
    "\0\62\0\u448e\0\u44c0\0\u44f2\0\u4524\0\u4556\0\u4588\0\u45ba"+
    "\0\u45ec\0\u461e\0\u4650\0\u4682\0\u028a\0\62\0\u46b4\0\u46e6"+
    "\0\u4718\0\u474a\0\u477c\0\u028a\0\62\0\u47ae\0\u47e0\0\u4812"+
    "\0\u4844\0\u4876\0\u48a8\0\u48da\0\u490c\0\u493e\0\u4970\0\u49a2"+
    "\0\u49d4\0\u4a06\0\u028a\0\u4a38\0\u4a6a\0\62\0\u4a9c\0\u4ace"+
    "\0\u028a\0\u4b00\0\u4b32\0\u4b64\0\u4b96\0\u4bc8\0\62\0\u4bfa"+
    "\0\u4c2c\0\u028a\0\62\0\u4c5e\0\u028a\0\62\0\u4c90\0\u028a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[472];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\2\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\25\1\32\1\33\1\25\1\34\1\35"+
    "\2\25\1\36\1\25\1\37\1\40\1\41\1\25\1\42"+
    "\3\25\1\2\1\25\1\43\1\44\1\45\63\0\2\3"+
    "\102\0\1\46\36\0\5\47\1\50\47\47\1\51\4\47"+
    "\2\6\2\0\56\6\7\0\1\52\17\0\1\53\1\54"+
    "\1\0\1\55\4\0\1\56\32\0\1\57\70\0\1\60"+
    "\1\0\1\20\63\0\1\61\61\0\1\62\61\0\1\63"+
    "\57\0\1\25\3\0\20\25\1\64\7\25\1\0\1\25"+
    "\24\0\1\25\3\0\30\25\1\0\1\25\24\0\1\25"+
    "\3\0\10\25\1\65\4\25\1\66\12\25\1\0\1\25"+
    "\1\0\1\67\22\0\1\25\3\0\4\25\1\70\23\25"+
    "\1\0\1\25\24\0\1\25\3\0\12\25\1\71\1\25"+
    "\1\72\13\25\1\0\1\25\24\0\1\25\3\0\10\25"+
    "\1\73\17\25\1\0\1\25\1\0\1\74\22\0\1\75"+
    "\3\0\1\76\5\75\22\25\1\0\1\25\24\0\1\25"+
    "\3\0\14\25\1\77\13\25\1\0\1\25\24\0\1\25"+
    "\3\0\4\25\1\100\23\25\1\0\1\25\24\0\1\25"+
    "\3\0\10\25\1\101\4\25\1\102\12\25\1\0\1\25"+
    "\1\0\1\103\22\0\1\25\3\0\1\104\27\25\1\0"+
    "\1\25\24\0\1\25\3\0\4\25\1\105\10\25\1\106"+
    "\12\25\1\0\1\25\24\0\1\25\3\0\10\25\1\107"+
    "\17\25\1\0\1\25\1\0\1\110\22\0\1\25\3\0"+
    "\10\25\1\111\17\25\1\0\1\25\1\0\1\112\22\0"+
    "\1\25\3\0\1\113\3\25\1\114\23\25\1\0\1\25"+
    "\62\0\1\115\43\0\1\116\55\0\1\110\22\0\1\110"+
    "\1\0\2\47\2\0\56\47\7\0\1\117\114\0\1\120"+
    "\50\0\1\121\65\0\1\122\22\0\1\122\32\0\1\123"+
    "\51\0\1\124\61\0\1\25\3\0\10\25\1\125\17\25"+
    "\1\0\1\25\1\0\1\126\22\0\1\25\3\0\20\25"+
    "\1\127\7\25\1\0\1\25\24\0\1\25\3\0\12\25"+
    "\1\130\1\131\14\25\1\0\1\25\50\0\1\132\35\0"+
    "\1\25\3\0\5\25\1\133\22\25\1\0\1\25\24\0"+
    "\1\25\3\0\10\25\1\134\17\25\1\0\1\25\1\0"+
    "\1\135\22\0\1\25\3\0\22\25\1\136\5\25\1\0"+
    "\1\25\24\0\1\25\3\0\6\25\1\137\5\25\1\140"+
    "\13\25\1\0\1\25\36\0\1\141\5\0\1\142\41\0"+
    "\1\143\3\0\6\143\22\25\1\0\1\25\24\0\1\143"+
    "\3\0\2\143\1\144\3\143\22\25\1\0\1\25\24\0"+
    "\1\25\3\0\10\25\1\145\17\25\1\0\1\25\1\0"+
    "\1\146\22\0\1\25\3\0\4\25\1\147\15\25\1\150"+
    "\5\25\1\0\1\25\24\0\1\25\3\0\4\25\1\151"+
    "\23\25\1\0\1\25\24\0\1\25\3\0\21\25\1\152"+
    "\6\25\1\0\1\25\2\0\1\153\31\0\1\154\51\0"+
    "\1\25\3\0\20\25\1\155\7\25\1\0\1\25\24\0"+
    "\1\25\3\0\2\25\1\156\25\25\1\0\1\25\24\0"+
    "\1\25\3\0\13\25\1\157\14\25\1\0\1\25\24\0"+
    "\1\25\3\0\13\25\1\160\14\25\1\0\1\25\43\0"+
    "\1\161\42\0\1\25\3\0\20\25\1\162\7\25\1\0"+
    "\1\25\24\0\1\25\3\0\20\25\1\163\7\25\1\0"+
    "\1\25\40\0\1\146\22\0\1\146\10\0\1\164\111\0"+
    "\1\165\54\0\1\166\62\0\1\141\75\0\1\167\33\0"+
    "\1\25\3\0\1\170\27\25\1\0\1\25\30\0\1\171"+
    "\55\0\1\25\3\0\2\25\1\172\25\25\1\0\1\25"+
    "\24\0\1\25\3\0\15\25\1\173\12\25\1\0\1\25"+
    "\24\0\1\25\3\0\10\25\1\174\17\25\1\0\1\25"+
    "\1\0\1\175\30\0\1\176\53\0\1\25\3\0\1\177"+
    "\27\25\1\0\1\25\24\0\1\25\3\0\16\25\1\200"+
    "\11\25\1\0\1\25\46\0\1\201\37\0\1\25\3\0"+
    "\15\25\1\202\12\25\1\0\1\25\24\0\1\25\3\0"+
    "\23\25\1\203\4\25\1\0\1\25\24\0\1\25\3\0"+
    "\13\25\1\204\5\25\1\205\6\25\1\0\1\25\2\0"+
    "\1\206\50\0\1\207\51\0\1\210\5\0\1\206\12\0"+
    "\1\206\21\0\1\211\3\0\6\211\22\25\1\0\1\25"+
    "\24\0\1\211\3\0\4\211\1\212\1\211\22\25\1\0"+
    "\1\25\24\0\1\25\3\0\2\25\1\213\25\25\1\0"+
    "\1\25\32\0\1\214\53\0\1\25\3\0\20\25\1\215"+
    "\7\25\1\0\1\25\24\0\1\25\3\0\20\25\1\216"+
    "\7\25\1\0\1\25\24\0\1\25\3\0\14\25\1\217"+
    "\13\25\1\0\1\25\24\0\1\25\3\0\22\25\1\220"+
    "\5\25\1\0\1\25\52\0\1\221\53\0\1\222\41\0"+
    "\1\25\3\0\1\223\27\25\1\0\1\25\24\0\1\25"+
    "\3\0\22\25\1\224\5\25\1\0\1\25\24\0\1\25"+
    "\3\0\1\25\1\225\26\25\1\0\1\25\24\0\1\25"+
    "\3\0\4\25\1\226\23\25\1\0\1\25\34\0\1\227"+
    "\51\0\1\25\3\0\3\25\1\230\24\25\1\0\1\25"+
    "\45\0\1\231\44\0\1\232\101\0\1\233\35\0\1\25"+
    "\3\0\12\25\1\234\15\25\1\0\1\25\42\0\1\235"+
    "\43\0\1\25\3\0\23\25\1\236\4\25\1\0\1\25"+
    "\24\0\1\25\3\0\20\25\1\237\7\25\1\0\1\25"+
    "\24\0\1\25\3\0\2\25\1\240\25\25\1\0\1\25"+
    "\32\0\1\241\102\0\1\242\32\0\1\25\3\0\23\25"+
    "\1\243\4\25\1\0\1\25\24\0\1\25\3\0\21\25"+
    "\1\244\6\25\1\0\1\25\2\0\1\245\46\0\1\245"+
    "\12\0\1\245\21\0\1\25\3\0\14\25\1\246\13\25"+
    "\1\0\1\25\24\0\1\25\3\0\20\25\1\247\7\25"+
    "\1\0\1\25\24\0\1\25\3\0\10\25\1\250\17\25"+
    "\1\0\1\25\1\0\1\251\22\0\1\25\3\0\10\25"+
    "\1\252\17\25\1\0\1\25\1\0\1\253\36\0\1\253"+
    "\22\0\1\253\46\0\1\254\51\0\1\251\22\0\1\251"+
    "\22\0\1\255\3\0\6\255\22\25\1\0\1\25\24\0"+
    "\1\255\3\0\6\255\12\25\1\256\7\25\1\0\1\25"+
    "\24\0\1\25\3\0\10\25\1\257\17\25\1\0\1\25"+
    "\1\0\1\260\36\0\1\260\22\0\1\260\22\0\1\25"+
    "\3\0\1\261\27\25\1\0\1\25\24\0\1\25\3\0"+
    "\22\25\1\262\5\25\1\0\1\25\24\0\1\25\3\0"+
    "\20\25\1\263\7\25\1\0\1\25\50\0\1\264\63\0"+
    "\1\265\33\0\1\25\3\0\12\25\1\266\15\25\1\0"+
    "\1\25\24\0\1\25\3\0\1\267\27\25\1\0\1\25"+
    "\24\0\1\25\3\0\15\25\1\270\12\25\1\0\1\25"+
    "\24\0\1\25\3\0\21\25\1\271\6\25\1\0\1\25"+
    "\2\0\1\272\46\0\1\272\12\0\1\272\21\0\1\25"+
    "\3\0\1\273\27\25\1\0\1\25\50\0\1\274\64\0"+
    "\1\275\36\0\1\276\55\0\1\25\3\0\12\25\1\277"+
    "\15\25\1\0\1\25\24\0\1\25\3\0\30\25\1\0"+
    "\1\300\24\0\1\25\3\0\30\25\1\0\1\301\61\0"+
    "\1\302\42\0\1\303\43\0\1\25\3\0\12\25\1\304"+
    "\15\25\1\0\1\25\24\0\1\25\3\0\4\25\1\305"+
    "\23\25\1\0\1\25\34\0\1\306\51\0\1\25\3\0"+
    "\2\25\1\307\25\25\1\0\1\25\24\0\1\25\3\0"+
    "\1\310\27\25\1\0\1\25\24\0\1\25\3\0\4\25"+
    "\1\311\23\25\1\0\1\25\34\0\1\312\55\0\1\313"+
    "\55\0\1\314\3\0\6\314\22\25\1\0\1\25\24\0"+
    "\1\25\3\0\15\25\1\315\12\25\1\0\1\25\45\0"+
    "\1\316\40\0\1\25\3\0\30\25\1\0\1\317\24\0"+
    "\1\25\3\0\20\25\1\320\7\25\1\0\1\25\24\0"+
    "\1\25\3\0\1\321\27\25\1\0\1\25\30\0\1\322"+
    "\101\0\1\323\35\0\1\25\3\0\4\25\1\324\23\25"+
    "\1\0\1\25\24\0\1\25\3\0\14\25\1\325\13\25"+
    "\1\0\1\25\24\0\1\25\3\0\30\25\1\0\1\326"+
    "\61\0\1\327\24\0\1\25\3\0\14\25\1\330\13\25"+
    "\1\0\1\25\61\0\1\331\42\0\1\332\100\0\1\333"+
    "\24\0\1\25\3\0\15\25\1\334\12\25\1\0\1\25"+
    "\24\0\1\25\3\0\1\25\1\335\11\25\1\336\5\25"+
    "\1\337\1\340\5\25\1\0\1\25\2\0\1\341\21\0"+
    "\1\25\3\0\21\25\1\342\6\25\1\0\1\25\2\0"+
    "\1\343\46\0\1\343\12\0\1\343\42\0\1\344\40\0"+
    "\1\25\3\0\22\25\1\345\5\25\1\0\1\25\24\0"+
    "\1\25\3\0\4\25\1\346\23\25\1\0\1\25\24\0"+
    "\1\25\3\0\30\25\1\0\1\347\24\0\1\25\3\0"+
    "\14\25\1\350\13\25\1\0\1\25\44\0\1\351\76\0"+
    "\1\352\24\0\1\353\3\0\6\353\22\25\1\0\1\25"+
    "\24\0\1\25\3\0\1\25\1\354\11\25\1\355\5\25"+
    "\1\356\6\25\1\0\1\25\2\0\1\357\21\0\1\25"+
    "\3\0\1\360\27\25\1\0\1\25\24\0\1\25\3\0"+
    "\20\25\1\361\7\25\1\0\1\25\50\0\1\362\41\0"+
    "\1\363\55\0\1\25\3\0\12\25\1\364\15\25\1\0"+
    "\1\25\24\0\1\25\3\0\6\25\1\365\21\25\1\0"+
    "\1\25\24\0\1\25\3\0\14\25\1\366\13\25\1\0"+
    "\1\25\44\0\1\367\41\0\1\25\3\0\1\370\27\25"+
    "\1\0\1\25\31\0\1\371\11\0\1\372\5\0\1\341"+
    "\1\373\11\0\1\341\47\0\1\374\40\0\1\375\11\0"+
    "\1\376\5\0\1\357\12\0\1\357\21\0\1\25\3\0"+
    "\12\25\1\377\15\25\1\0\1\25\24\0\1\25\3\0"+
    "\10\25\1\u0100\17\25\1\0\1\25\1\0\1\u0101\22\0"+
    "\1\25\3\0\10\25\1\u0102\17\25\1\0\1\25\1\0"+
    "\1\u0103\22\0\1\25\3\0\4\25\1\u0104\23\25\1\0"+
    "\1\25\40\0\1\u0103\22\0\1\u0103\22\0\1\25\3\0"+
    "\1\u0105\27\25\1\0\1\25\30\0\1\u0106\55\0\1\25"+
    "\3\0\21\25\1\u0107\6\25\1\0\1\25\2\0\1\u0108"+
    "\21\0\1\25\3\0\1\25\1\u0109\11\25\1\u010a\5\25"+
    "\1\u010b\6\25\1\0\1\25\2\0\1\u010c\21\0\1\25"+
    "\3\0\22\25\1\u010d\5\25\1\0\1\25\52\0\1\u010e"+
    "\40\0\1\u010f\11\0\1\u0110\5\0\1\u010c\12\0\1\u010c"+
    "\21\0\1\25\3\0\12\25\1\u0111\15\25\1\0\1\25"+
    "\24\0\1\25\3\0\10\25\1\u0112\17\25\1\0\1\25"+
    "\1\0\1\u0113\22\0\1\25\3\0\10\25\1\u0114\17\25"+
    "\1\0\1\25\1\0\1\u0115\36\0\1\u0115\22\0\1\u0115"+
    "\22\0\1\25\3\0\21\25\1\u0116\6\25\1\0\1\25"+
    "\2\0\1\u0117\46\0\1\u0117\12\0\1\u0117\21\0\1\25"+
    "\3\0\15\25\1\u0118\12\25\1\0\1\25\24\0\1\25"+
    "\3\0\23\25\1\u0119\4\25\1\0\1\25\24\0\1\25"+
    "\3\0\4\25\1\u011a\23\25\1\0\1\25\34\0\1\u011b"+
    "\67\0\1\u011c\57\0\1\u0101\22\0\1\u0101\32\0\1\u011d"+
    "\67\0\1\u011e\57\0\1\u0113\22\0\1\u0113\22\0\1\25"+
    "\3\0\15\25\1\u011f\12\25\1\0\1\25\24\0\1\25"+
    "\3\0\4\25\1\u0120\23\25\1\0\1\25\34\0\1\u0121"+
    "\51\0\1\25\3\0\26\25\1\u0122\1\25\1\0\1\25"+
    "\24\0\1\25\3\0\14\25\1\u0123\13\25\1\0\1\25"+
    "\44\0\1\u0124\41\0\1\25\3\0\12\25\1\u0125\15\25"+
    "\1\0\1\25\24\0\1\25\3\0\10\25\1\u0126\17\25"+
    "\1\0\1\25\1\0\1\u0127\22\0\1\25\3\0\10\25"+
    "\1\u0128\17\25\1\0\1\25\1\0\1\u0129\36\0\1\u0129"+
    "\22\0\1\u0129\22\0\1\25\3\0\20\25\1\u012a\7\25"+
    "\1\0\1\25\50\0\1\u012b\53\0\1\u012c\57\0\1\u0127"+
    "\22\0\1\u0127\22\0\1\25\3\0\15\25\1\u012d\12\25"+
    "\1\0\1\25\24\0\1\25\3\0\4\25\1\u012e\23\25"+
    "\1\0\1\25\34\0\1\u012f\51\0\1\25\3\0\27\25"+
    "\1\u0130\1\0\1\25\57\0\1\u0131\26\0\1\25\3\0"+
    "\6\25\1\u0132\21\25\1\0\1\25\24\0\1\25\3\0"+
    "\12\25\1\u0133\15\25\1\0\1\25\24\0\1\25\3\0"+
    "\25\25\1\u0134\2\25\1\0\1\25\55\0\1\u0135\51\0"+
    "\1\u0136\72\0\1\u0137\50\0\1\u0138\40\0\1\25\3\0"+
    "\17\25\1\u0139\10\25\1\0\1\25\24\0\1\25\3\0"+
    "\14\25\1\u013a\13\25\1\0\1\25\44\0\1\u013b\41\0"+
    "\1\25\3\0\22\25\1\u013c\5\25\1\0\1\25\24\0"+
    "\1\25\3\0\21\25\1\u013d\6\25\1\0\1\25\2\0"+
    "\1\u013e\46\0\1\u013e\12\0\1\u013e\21\0\1\25\3\0"+
    "\15\25\1\u013f\12\25\1\0\1\25\24\0\1\25\3\0"+
    "\4\25\1\u0140\23\25\1\0\1\25\34\0\1\u0141\51\0"+
    "\1\25\3\0\1\u0142\27\25\1\0\1\25\30\0\1\u0143"+
    "\76\0\1\u0144\40\0\1\25\3\0\17\25\1\u0145\10\25"+
    "\1\0\1\25\24\0\1\25\3\0\14\25\1\u0146\13\25"+
    "\1\0\1\25\44\0\1\u0147\41\0\1\25\3\0\4\25"+
    "\1\u0148\23\25\1\0\1\25\34\0\1\u0149\51\0\1\25"+
    "\3\0\20\25\1\u014a\7\25\1\0\1\25\24\0\1\25"+
    "\3\0\15\25\1\u014b\12\25\1\0\1\25\24\0\1\25"+
    "\3\0\30\25\1\0\1\u014c\61\0\1\u014d\47\0\1\u014e"+
    "\64\0\1\u014f\56\0\1\u0150\36\0\1\25\3\0\23\25"+
    "\1\u0151\4\25\1\0\1\25\24\0\1\25\3\0\22\25"+
    "\1\u0152\5\25\1\0\1\25\52\0\1\u0153\33\0\1\25"+
    "\3\0\15\25\1\u0154\12\25\1\0\1\25\24\0\1\25"+
    "\3\0\17\25\1\u0155\10\25\1\0\1\25\24\0\1\25"+
    "\3\0\14\25\1\u0156\13\25\1\0\1\25\44\0\1\u0157"+
    "\41\0\1\25\3\0\21\25\1\u0158\6\25\1\0\1\25"+
    "\2\0\1\u0159\46\0\1\u0159\12\0\1\u0159\44\0\1\u015a"+
    "\36\0\1\25\3\0\23\25\1\u015b\4\25\1\0\1\25"+
    "\24\0\1\25\3\0\22\25\1\u015c\5\25\1\0\1\25"+
    "\52\0\1\u015d\33\0\1\25\3\0\30\25\1\0\1\u015e"+
    "\61\0\1\u015f\24\0\1\25\3\0\1\u0160\27\25\1\0"+
    "\1\25\24\0\1\25\3\0\30\25\1\0\1\u0161\24\0"+
    "\1\25\3\0\20\25\1\u0162\7\25\1\0\1\25\50\0"+
    "\1\u0163\64\0\1\u0164\53\0\1\u0165\67\0\1\u0166\32\0"+
    "\1\25\3\0\4\25\1\u0167\23\25\1\0\1\25\24\0"+
    "\1\25\3\0\20\25\1\u0168\7\25\1\0\1\25\50\0"+
    "\1\u0169\35\0\1\25\3\0\30\25\1\0\1\u016a\24\0"+
    "\1\25\3\0\23\25\1\u016b\4\25\1\0\1\25\24\0"+
    "\1\25\3\0\22\25\1\u016c\5\25\1\0\1\25\52\0"+
    "\1\u016d\62\0\1\u016e\32\0\1\25\3\0\4\25\1\u016f"+
    "\23\25\1\0\1\25\24\0\1\25\3\0\20\25\1\u0170"+
    "\7\25\1\0\1\25\50\0\1\u0171\35\0\1\25\3\0"+
    "\1\25\1\u0172\11\25\1\u0173\5\25\1\u0174\6\25\1\0"+
    "\1\25\2\0\1\u0175\26\0\1\u0176\11\0\1\u0177\5\0"+
    "\1\u0175\12\0\1\u0175\21\0\1\25\3\0\13\25\1\u0178"+
    "\14\25\1\0\1\25\24\0\1\25\3\0\20\25\1\u0179"+
    "\7\25\1\0\1\25\24\0\1\25\3\0\15\25\1\u017a"+
    "\12\25\1\0\1\25\45\0\1\u017b\50\0\1\u017c\106\0"+
    "\1\u017d\34\0\1\u017e\51\0\1\25\3\0\1\u017f\27\25"+
    "\1\0\1\25\30\0\1\u0180\55\0\1\25\3\0\1\25"+
    "\1\u0181\11\25\1\u0182\5\25\1\u0183\6\25\1\0\1\25"+
    "\2\0\1\u0184\21\0\1\25\3\0\4\25\1\u0185\23\25"+
    "\1\0\1\25\24\0\1\25\3\0\20\25\1\u0186\7\25"+
    "\1\0\1\25\50\0\1\u0187\45\0\1\u0188\51\0\1\25"+
    "\3\0\1\u0189\27\25\1\0\1\25\30\0\1\u018a\55\0"+
    "\1\25\3\0\12\25\1\u018b\15\25\1\0\1\25\24\0"+
    "\1\25\3\0\10\25\1\u018c\17\25\1\0\1\25\1\0"+
    "\1\u018d\22\0\1\25\3\0\10\25\1\u018e\17\25\1\0"+
    "\1\25\1\0\1\u018f\36\0\1\u018f\22\0\1\u018f\40\0"+
    "\1\u0190\57\0\1\u018d\22\0\1\u018d\22\0\1\25\3\0"+
    "\15\25\1\u0191\12\25\1\0\1\25\24\0\1\25\3\0"+
    "\4\25\1\u0192\23\25\1\0\1\25\24\0\1\25\3\0"+
    "\13\25\1\u0193\14\25\1\0\1\25\43\0\1\u0194\47\0"+
    "\1\u0195\11\0\1\u0196\5\0\1\u0184\12\0\1\u0184\21\0"+
    "\1\25\3\0\21\25\1\u0197\6\25\1\0\1\25\2\0"+
    "\1\u0198\46\0\1\u0198\12\0\1\u0198\21\0\1\25\3\0"+
    "\12\25\1\u0199\15\25\1\0\1\25\24\0\1\25\3\0"+
    "\10\25\1\u019a\17\25\1\0\1\25\1\0\1\u019b\22\0"+
    "\1\25\3\0\10\25\1\u019c\17\25\1\0\1\25\1\0"+
    "\1\u019d\36\0\1\u019d\22\0\1\u019d\22\0\1\25\3\0"+
    "\1\u019e\27\25\1\0\1\25\30\0\1\u019f\55\0\1\25"+
    "\3\0\21\25\1\u01a0\6\25\1\0\1\25\2\0\1\u01a1"+
    "\46\0\1\u01a1\12\0\1\u01a1\21\0\1\25\3\0\15\25"+
    "\1\u01a2\12\25\1\0\1\25\24\0\1\25\3\0\4\25"+
    "\1\u01a3\23\25\1\0\1\25\34\0\1\u01a4\72\0\1\u01a5"+
    "\40\0\1\25\3\0\3\25\1\u01a6\24\25\1\0\1\25"+
    "\24\0\1\25\3\0\1\u01a7\27\25\1\0\1\25\30\0"+
    "\1\u01a8\73\0\1\u01a9\57\0\1\u019b\22\0\1\u019b\22\0"+
    "\1\25\3\0\15\25\1\u01aa\12\25\1\0\1\25\24\0"+
    "\1\25\3\0\4\25\1\u01ab\23\25\1\0\1\25\34\0"+
    "\1\u01ac\51\0\1\25\3\0\21\25\1\u01ad\6\25\1\0"+
    "\1\25\2\0\1\u01ae\46\0\1\u01ae\12\0\1\u01ae\21\0"+
    "\1\25\3\0\17\25\1\u01af\10\25\1\0\1\25\24\0"+
    "\1\25\3\0\14\25\1\u01b0\13\25\1\0\1\25\44\0"+
    "\1\u01b1\64\0\1\u01b2\36\0\1\25\3\0\15\25\1\u01b3"+
    "\12\25\1\0\1\25\24\0\1\25\3\0\14\25\1\u01b4"+
    "\13\25\1\0\1\25\44\0\1\u01b5\62\0\1\u01b6\40\0"+
    "\1\25\3\0\17\25\1\u01b7\10\25\1\0\1\25\24\0"+
    "\1\25\3\0\14\25\1\u01b8\13\25\1\0\1\25\44\0"+
    "\1\u01b9\41\0\1\25\3\0\23\25\1\u01ba\4\25\1\0"+
    "\1\25\24\0\1\25\3\0\22\25\1\u01bb\5\25\1\0"+
    "\1\25\52\0\1\u01bc\62\0\1\u01bd\32\0\1\25\3\0"+
    "\14\25\1\u01be\13\25\1\0\1\25\47\0\1\u01bf\36\0"+
    "\1\25\3\0\23\25\1\u01c0\4\25\1\0\1\25\24\0"+
    "\1\25\3\0\22\25\1\u01c1\5\25\1\0\1\25\52\0"+
    "\1\u01c2\33\0\1\25\3\0\4\25\1\u01c3\23\25\1\0"+
    "\1\25\24\0\1\25\3\0\20\25\1\u01c4\7\25\1\0"+
    "\1\25\50\0\1\u01c5\45\0\1\u01c6\51\0\1\25\3\0"+
    "\3\25\1\u01c7\24\25\1\0\1\25\53\0\1\u01c8\32\0"+
    "\1\25\3\0\4\25\1\u01c9\23\25\1\0\1\25\24\0"+
    "\1\25\3\0\20\25\1\u01ca\7\25\1\0\1\25\50\0"+
    "\1\u01cb\35\0\1\25\3\0\1\u01cc\27\25\1\0\1\25"+
    "\30\0\1\u01cd\55\0\1\25\3\0\4\25\1\u01ce\23\25"+
    "\1\0\1\25\34\0\1\u01cf\51\0\1\25\3\0\1\u01d0"+
    "\27\25\1\0\1\25\30\0\1\u01d1\55\0\1\25\3\0"+
    "\21\25\1\u01d2\6\25\1\0\1\25\2\0\1\u01d3\46\0"+
    "\1\u01d3\12\0\1\u01d3\21\0\1\25\3\0\1\u01d4\27\25"+
    "\1\0\1\25\24\0\1\25\3\0\21\25\1\u01d5\6\25"+
    "\1\0\1\25\2\0\1\u01d6\46\0\1\u01d6\12\0\1\u01d6"+
    "\21\0\1\25\3\0\3\25\1\u01d7\24\25\1\0\1\25"+
    "\24\0\1\25\3\0\15\25\1\u01d8\12\25\1\0\1\25"+
    "\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[19650];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\7\11\26\1\1\11\1\0\1\11"+
    "\6\0\1\11\1\0\3\11\3\1\1\0\4\1\1\0"+
    "\6\1\1\0\4\1\1\11\1\1\1\0\2\1\1\11"+
    "\6\0\2\1\1\0\3\1\1\0\2\1\1\0\3\1"+
    "\1\0\4\1\1\0\4\1\2\0\4\1\1\0\2\1"+
    "\1\11\3\0\1\1\1\0\3\1\2\0\2\1\1\0"+
    "\4\1\3\0\3\1\1\0\4\1\2\0\4\1\1\0"+
    "\1\1\3\0\1\1\1\11\3\1\2\0\2\1\1\0"+
    "\3\1\1\0\1\1\1\11\1\0\3\1\1\0\3\1"+
    "\2\0\4\1\1\0\1\1\3\0\3\1\2\0\2\1"+
    "\1\11\3\1\2\0\2\1\1\11\3\1\2\0\3\1"+
    "\1\0\1\1\3\0\5\1\1\0\1\1\1\0\1\11"+
    "\4\1\2\0\4\1\1\0\2\1\1\11\1\0\3\1"+
    "\1\0\1\1\3\0\1\11\2\0\2\1\1\0\1\1"+
    "\1\11\2\1\1\0\1\1\1\11\3\1\1\0\1\1"+
    "\3\0\2\1\1\0\3\1\1\11\3\1\4\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\0\1\1\1\11\1\1"+
    "\2\0\2\1\1\0\1\1\1\0\3\1\4\0\2\1"+
    "\1\0\2\1\1\11\2\1\1\0\1\1\2\0\2\1"+
    "\1\0\1\1\1\0\3\1\4\0\2\1\1\0\3\1"+
    "\1\0\1\1\1\11\1\0\2\1\1\0\1\1\1\0"+
    "\3\1\4\0\2\1\1\0\3\1\2\0\2\1\1\0"+
    "\3\1\3\0\3\1\1\0\1\11\1\0\1\11\1\1"+
    "\1\0\3\1\1\0\2\1\1\0\1\11\1\1\1\0"+
    "\2\1\1\0\1\1\1\11\1\0\3\1\3\0\1\1"+
    "\1\11\2\1\1\0\1\1\1\11\1\1\1\0\1\1"+
    "\1\11\2\1\2\0\2\1\2\0\2\1\1\0\1\1"+
    "\1\11\2\1\2\0\2\1\1\11\1\0\2\1\1\0"+
    "\2\1\2\0\1\1\1\0\2\1\1\0\2\1\1\0"+
    "\1\11\1\1\1\0\2\1\1\0\1\1\1\0\1\1"+
    "\1\11\1\1\1\0\1\1\1\11\2\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[472];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
   /*---------------------------------------------
        Codigo para el manejo de errores
    -----------------------------------------------*/

    private List<String> errorList = new java.util.ArrayList<>();
    
    public List<String> getLexicalErrors(){
        return this.errorList;
    }

     /*-----------------------------------------------
              Codigo para el parser
        -------------------------------------------------*/
        private Symbol symbol(int type){
            return new Symbol(type, yyline+1, yycolumn+1);
        }

        private Symbol symbol(int type, Object value){
            return new Symbol(type, yyline+1, yycolumn+1, value);
        }

         private void error(String message){
         errorList.add("Error en la linea: " + (yyline+1) + ", columna: " + (yycolumn+1) + " : " + message);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Error léxico en línea " + (yyline+1) + ", columna " + (yycolumn+1) + ": '" + yytext() + "'");
            }
          // fall through
          case 65: break;
          case 2:
            { /* skip */
            }
          // fall through
          case 66: break;
          case 3:
            { return symbol(sym.NOT);
            }
          // fall through
          case 67: break;
          case 4:
            { /* comentario */
            }
          // fall through
          case 68: break;
          case 5:
            { return symbol(sym.PAR_IZQ);
            }
          // fall through
          case 69: break;
          case 6:
            { return symbol(sym.PAR_DER);
            }
          // fall through
          case 70: break;
          case 7:
            { return symbol(sym.POR);
            }
          // fall through
          case 71: break;
          case 8:
            { return symbol(sym.MAS);
            }
          // fall through
          case 72: break;
          case 9:
            { return symbol(sym.COMA);
            }
          // fall through
          case 73: break;
          case 10:
            { return symbol(sym.MENOS);
            }
          // fall through
          case 74: break;
          case 11:
            { return symbol(sym.DIV);
            }
          // fall through
          case 75: break;
          case 12:
            { return symbol(sym.ENTERO, yytext());
            }
          // fall through
          case 76: break;
          case 13:
            { return symbol(sym.MENOR);
            }
          // fall through
          case 77: break;
          case 14:
            { return symbol(sym.ASIG);
            }
          // fall through
          case 78: break;
          case 15:
            { return symbol(sym.MAYOR);
            }
          // fall through
          case 79: break;
          case 16:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 80: break;
          case 17:
            { return symbol(sym.PIPE);
            }
          // fall through
          case 81: break;
          case 18:
            { return symbol(sym.DIFERENTE);
            }
          // fall through
          case 82: break;
          case 19:
            { return symbol(sym.CADENA, yytext());
            }
          // fall through
          case 83: break;
          case 20:
            { return symbol(sym.AND);
            }
          // fall through
          case 84: break;
          case 21:
            { return symbol(sym.MENOR_IGUAL);
            }
          // fall through
          case 85: break;
          case 22:
            { return symbol(sym.IGUALDAD);
            }
          // fall through
          case 86: break;
          case 23:
            { return symbol(sym.MAYOR_IGUAL);
            }
          // fall through
          case 87: break;
          case 24:
            { return symbol(sym.SI);
            }
          // fall through
          case 88: break;
          case 25:
            { return symbol(sym.OR);
            }
          // fall through
          case 89: break;
          case 26:
            { return symbol(sym.DECIMAL, yytext());
            }
          // fall through
          case 90: break;
          case 27:
            { return symbol(sym.FIN);
            }
          // fall through
          case 91: break;
          case 28:
            { return symbol(sym.VAR);
            }
          // fall through
          case 92: break;
          case 29:
            { return symbol(sym.SEP_SECCIONES);
            }
          // fall through
          case 93: break;
          case 30:
            { return symbol(sym.LEER);
            }
          // fall through
          case 94: break;
          case 31:
            { return symbol(sym.FONT_ARIAL);
            }
          // fall through
          case 95: break;
          case 32:
            { return symbol(sym.FINSI);
            }
          // fall through
          case 96: break;
          case 33:
            { return symbol(sym.HACER);
            }
          // fall through
          case 97: break;
          case 34:
            { return symbol(sym.FIG_ROMBO);
            }
          // fall through
          case 98: break;
          case 35:
            { return symbol(sym.FIG_ELIPSE);
            }
          // fall through
          case 99: break;
          case 36:
            { return symbol(sym.INICIO);
            }
          // fall through
          case 100: break;
          case 37:
            { return symbol(sym.FIG_CIRCULO);
            }
          // fall through
          case 101: break;
          case 38:
            { return symbol(sym.CONF_DEFAULT);
            }
          // fall through
          case 102: break;
          case 39:
            { return symbol(sym.HEX, yytext());
            }
          // fall through
          case 103: break;
          case 40:
            { return symbol(sym.MOSTRAR);
            }
          // fall through
          case 104: break;
          case 41:
            { return symbol(sym.FONT_VERDANA);
            }
          // fall through
          case 105: break;
          case 42:
            { return symbol(sym.CONF_COLOR_SI);
            }
          // fall through
          case 106: break;
          case 43:
            { return symbol(sym.ENTONCES);
            }
          // fall through
          case 107: break;
          case 44:
            { return symbol(sym.CONF_LETRA_SI);
            }
          // fall through
          case 108: break;
          case 45:
            { return symbol(sym.MIENTRAS);
            }
          // fall through
          case 109: break;
          case 46:
            { return symbol(sym.CONF_FIGURA_SI);
            }
          // fall through
          case 110: break;
          case 47:
            { return symbol(sym.FONT_COMIC_SANS);
            }
          // fall through
          case 111: break;
          case 48:
            { return symbol(sym.FIG_RECTANGULO);
            }
          // fall through
          case 112: break;
          case 49:
            { return symbol(sym.FINMIENTRAS);
            }
          // fall through
          case 113: break;
          case 50:
            { return symbol(sym.CONF_COLOR_BLOQUE);
            }
          // fall through
          case 114: break;
          case 51:
            { return symbol(sym.CONF_LETRA_BLOQUE);
            }
          // fall through
          case 115: break;
          case 52:
            { return symbol(sym.CONF_FIGURA_BLOQUE);
            }
          // fall through
          case 116: break;
          case 53:
            { return symbol(sym.CONF_LETRA_SIZE_SI);
            }
          // fall through
          case 117: break;
          case 54:
            { return symbol(sym.FIG_PARALELOGRAMO);
            }
          // fall through
          case 118: break;
          case 55:
            { return symbol(sym.CONF_COLOR_MIENTRAS);
            }
          // fall through
          case 119: break;
          case 56:
            { return symbol(sym.CONF_COLOR_TEXTO_SI);
            }
          // fall through
          case 120: break;
          case 57:
            { return symbol(sym.CONF_LETRA_MIENTRAS);
            }
          // fall through
          case 121: break;
          case 58:
            { return symbol(sym.CONF_FIGURA_MIENTRAS);
            }
          // fall through
          case 122: break;
          case 59:
            { return symbol(sym.FONT_TIMES_NEW_ROMAN);
            }
          // fall through
          case 123: break;
          case 60:
            { return symbol(sym.CONF_LETRA_SIZE_BLOQUE);
            }
          // fall through
          case 124: break;
          case 61:
            { return symbol(sym.CONF_COLOR_TEXTO_BLOQUE);
            }
          // fall through
          case 125: break;
          case 62:
            { return symbol(sym.CONF_LETRA_SIZE_MIENTRAS);
            }
          // fall through
          case 126: break;
          case 63:
            { return symbol(sym.CONF_COLOR_TEXTO_MIENTRAS);
            }
          // fall through
          case 127: break;
          case 64:
            { return symbol(sym.FIG_RECTANGULO_REDONDEADO);
            }
          // fall through
          case 128: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
