
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package paboomi.practica1_compi1_1s_2026.backend.analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_DER = 20;
  public static final int CONF_COLOR_TEXTO_SI = 33;
  public static final int POR = 16;
  public static final int FIG_ELIPSE = 48;
  public static final int FONT_TIMES_NEW_ROMAN = 55;
  public static final int ENTERO = 60;
  public static final int SI = 5;
  public static final int MOSTRAR = 11;
  public static final int DIFERENTE = 22;
  public static final int ENTONCES = 6;
  public static final int HEX = 62;
  public static final int FONT_VERDANA = 57;
  public static final int FIN = 3;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int CONF_LETRA_MIENTRAS = 41;
  public static final int FINMIENTRAS = 10;
  public static final int IGUALDAD = 21;
  public static final int OR = 28;
  public static final int MIENTRAS = 8;
  public static final int DIV = 17;
  public static final int FONT_COMIC_SANS = 56;
  public static final int FIG_ROMBO = 52;
  public static final int ID = 58;
  public static final int CONF_LETRA_SI = 36;
  public static final int CONF_COLOR_SI = 34;
  public static final int DECIMAL = 61;
  public static final int EOF = 0;
  public static final int ASIG = 18;
  public static final int CONF_LETRA_SIZE_BLOQUE = 47;
  public static final int CONF_FIGURA_MIENTRAS = 40;
  public static final int CONF_FIGURA_SI = 35;
  public static final int error = 1;
  public static final int SEP_SECCIONES = 13;
  public static final int COMA = 31;
  public static final int CADENA = 59;
  public static final int PIPE = 30;
  public static final int MENOS = 15;
  public static final int MENOR = 24;
  public static final int CONF_COLOR_BLOQUE = 44;
  public static final int PAR_IZQ = 19;
  public static final int MAYOR = 23;
  public static final int CONF_LETRA_SIZE_SI = 37;
  public static final int CONF_COLOR_TEXTO_BLOQUE = 43;
  public static final int CONF_COLOR_MIENTRAS = 39;
  public static final int FIG_RECTANGULO = 51;
  public static final int CONF_LETRA_BLOQUE = 46;
  public static final int FIG_RECTANGULO_REDONDEADO = 53;
  public static final int MAYOR_IGUAL = 25;
  public static final int FIG_CIRCULO = 49;
  public static final int LEER = 12;
  public static final int CONF_FIGURA_BLOQUE = 45;
  public static final int CONF_DEFAULT = 32;
  public static final int HACER = 9;
  public static final int CONF_COLOR_TEXTO_MIENTRAS = 38;
  public static final int INICIO = 2;
  public static final int MENOR_IGUAL = 26;
  public static final int CONF_LETRA_SIZE_MIENTRAS = 42;
  public static final int FINSI = 7;
  public static final int FONT_ARIAL = 54;
  public static final int FIG_PARALELOGRAMO = 50;
  public static final int VAR = 4;
  public static final int MAS = 14;
  public static final String[] terminalNames = new String[] {
      "EOF",
      "error",
      "INICIO",
      "FIN",
      "VAR",
      "SI",
      "ENTONCES",
      "FINSI",
      "MIENTRAS",
      "HACER",
      "FINMIENTRAS",
      "MOSTRAR",
      "LEER",
      "SEP_SECCIONES",
      "MAS",
      "MENOS",
      "POR",
      "DIV",
      "ASIG",
      "PAR_IZQ",
      "PAR_DER",
      "IGUALDAD",
      "DIFERENTE",
      "MAYOR",
      "MENOR",
      "MAYOR_IGUAL",
      "MENOR_IGUAL",
      "AND",
      "OR",
      "NOT",
      "PIPE",
      "COMA",
      "CONF_DEFAULT",
      "CONF_COLOR_TEXTO_SI",
      "CONF_COLOR_SI",
      "CONF_FIGURA_SI",
      "CONF_LETRA_SI",
      "CONF_LETRA_SIZE_SI",
      "CONF_COLOR_TEXTO_MIENTRAS",
      "CONF_COLOR_MIENTRAS",
      "CONF_FIGURA_MIENTRAS",
      "CONF_LETRA_MIENTRAS",
      "CONF_LETRA_SIZE_MIENTRAS",
      "CONF_COLOR_TEXTO_BLOQUE",
      "CONF_COLOR_BLOQUE",
      "CONF_FIGURA_BLOQUE",
      "CONF_LETRA_BLOQUE",
      "CONF_LETRA_SIZE_BLOQUE",
      "FIG_ELIPSE",
      "FIG_CIRCULO",
      "FIG_PARALELOGRAMO",
      "FIG_RECTANGULO",
      "FIG_ROMBO",
      "FIG_RECTANGULO_REDONDEADO",
      "FONT_ARIAL",
      "FONT_TIMES_NEW_ROMAN",
      "FONT_COMIC_SANS",
      "FONT_VERDANA",
      "ID",
      "CADENA",
      "ENTERO",
      "DECIMAL",
      "HEX"
  };
}
